# Configuration file for alacritty terminal

# terminal themes import
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# [shell]
# program = ""
# args = []

[font]
normal = { family = "ComicShannsMono Nerd Font", style = "Regular"}
bold = { family = "Hack Nerd Font", style = "Bold"}
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic"}
size = 13

